# fly.toml app configuration file generated for divemap-backend on 2025-07-27T16:43:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divemap-backend'
primary_region = 'fra'

[build]

[env]
  ACCESS_TOKEN_EXPIRE_MINUTES = '30'
  ALGORITHM = 'HS256'
  PYTHONPATH = '/app'
  SUSPICIOUS_PROXY_CHAIN_LENGTH = '6'

[processes]
  app = '/app/startup.sh'

[[mounts]]
  source = 'divemap_uploads'
  destination = '/app/uploads'

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 150

  [[http_service.checks]]
    grace_period = "20s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
