import { useState, useCallback } from 'react';
import toast from 'react-hot-toast';

import { sendChatMessage, submitChatFeedback } from '../api';

export const useChat = (context = {}) => {
  const [messages, setMessages] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId, setSessionId] = useState(null);

  const sendMessage = useCallback(
    async text => {
      if (!text.trim()) return;

      // 1. Add user message
      const userMessage = { role: 'user', content: text };
      setMessages(prev => [...prev, userMessage]);
      setIsLoading(true);

      try {
        // 2. Call API
        // Note: context can include { context_entity_id, context_entity_type, user_location }
        const response = await sendChatMessage(text, messages, {
          ...context,
          session_id: sessionId,
        });

        // Update session ID if it was generated by backend
        if (response.session_id && !sessionId) {
          setSessionId(response.session_id);
        }

        // 3. Add bot response
        const botMessage = {
          role: 'assistant',
          content: response.response,
          message_id: response.message_id,
          sources: response.sources,
          intent: response.intent,
        };
        setMessages(prev => [...prev, botMessage]);
      } catch (error) {
        console.error('Chat error:', error);
        toast.error('Failed to send message. Please try again.');
        // Add error message to chat
        setMessages(prev => [
          ...prev,
          {
            role: 'system',
            content: 'Sorry, I encountered an error. Please try again later.',
          },
        ]);
      } finally {
        setIsLoading(false);
      }
    },
    [messages, context]
  );

  const giveFeedback = useCallback(async (messageId, rating, category = null) => {
    try {
      // Find the assistant message and the preceding user message
      const assistantMsgIdx = messages.findIndex(m => m.message_id === messageId);
      const assistantMsg = messages[assistantMsgIdx];
      const userMsg = assistantMsgIdx > 0 ? messages[assistantMsgIdx - 1] : null;

      const debugData = {
        intent: assistantMsg?.intent,
        sources: assistantMsg?.sources,
      };

      await submitChatFeedback(
        messageId,
        rating,
        category,
        null, // comments
        userMsg?.content,
        assistantMsg?.content,
        debugData
      );
      toast.success('Thank you for your feedback!');

      // Update local state to reflect feedback (optional)
      setMessages(prev =>
        prev.map(msg => (msg.message_id === messageId ? { ...msg, user_rating: rating } : msg))
      );
    } catch (error) {
      console.error('Feedback error:', error);
    }
  }, []);

  const clearChat = useCallback(() => {
    setMessages([]);
    setSessionId(null);
  }, []);

  return {
    messages,
    sendMessage,
    isLoading,
    giveFeedback,
    clearChat,
  };
};
