# fly.toml app configuration file generated for divemap-db on 2025-07-27T17:30:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divemap-db'
primary_region = 'fra'

[build]

[[services]]
  internal_port = 3306
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[services.ports]]
    port = 3306
    handlers = []  # required for raw TCP services (like MySQL)
    force_https = false  # optional

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "60s"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[processes]
  app = '--datadir /data/mysql --mysql-native-password=ON'

# MySQL optimization environment variables for faster cold start
[env]
  # Skip non-essential initialization (helps startup time)
  MYSQL_SKIP_NAME_RESOLVE = "ON"
  MYSQL_SKIP_LOG_BIN = "ON"
  MYSQL_SKIP_EXTERNAL_LOCKING = "ON"
  MYSQL_INNODB_USE_NATIVE_AIO = "ON"
  
  # Memory optimization (reduces initialization overhead)
  MYSQL_INNODB_ADAPTIVE_HASH_INDEX = "OFF"
  MYSQL_INNODB_CHANGE_BUFFERING = "none"
  MYSQL_INNODB_CHECKSUM_ALGORITHM = "crc32"
  
  # Log file optimization (minimal startup impact)
  MYSQL_INNODB_LOG_FILE_SIZE = "256M"
  MYSQL_INNODB_LOG_FILES_IN_GROUP = "2"
  MYSQL_INNODB_LOG_BUFFER_SIZE = "16M"
  MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT = "2"
  MYSQL_INNODB_FLUSH_METHOD = "O_DIRECT"
  
  # I/O optimization (minimal startup impact)
  MYSQL_INNODB_IO_CAPACITY = "2000"
  MYSQL_INNODB_IO_CAPACITY_MAX = "4000"
  MYSQL_INNODB_READ_IO_THREADS = "4"
  MYSQL_INNODB_WRITE_IO_THREADS = "4"
  MYSQL_INNODB_PURGE_THREADS = "1"
  MYSQL_INNODB_PAGE_CLEANERS = "1"

# Add the following sections for all versions
[mounts]
  source = 'divemap_mysql_data'
  destination = '/data'

