# fly.toml app configuration file for divemap-nginx-proxy
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'divemap'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile.prod"

[env]
  NGINX_ENV = 'production'

[processes]
  app = 'nginx -g "daemon off;"'

# HTTP service configuration (Fly.io handles HTTPS termination)
[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Health checks
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

# VM configuration
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
