"""add_deco_time_limit_to_certification_level

Revision ID: 0053
Revises: 0052
Create Date: 2025-12-29 22:22:50.057678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0053'
down_revision = '0052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certification_levels', sa.Column('deco_time_limit', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    # Backfill data
    import json
    import os
    
    # Define tables for update
    certification_levels = sa.table('certification_levels',
        sa.column('id', sa.Integer),
        sa.column('diving_organization_id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('deco_time_limit', sa.String)
    )
    
    diving_organizations = sa.table('diving_organizations',
        sa.column('id', sa.Integer),
        sa.column('acronym', sa.String)
    )

    # Load data
    json_path = os.path.join(os.path.dirname(__file__), '../../diving_certifications_data.json')
    if not os.path.exists(json_path):
        json_path = '/app/diving_certifications_data.json'

    if os.path.exists(json_path):
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            bind = op.get_bind()
            session = sa.orm.Session(bind=bind)
            
            for org_data in data:
                # Find org id
                org = session.query(diving_organizations).filter_by(acronym=org_data['acronym']).first()
                if not org:
                    continue
                    
                for cert in org_data['certifications']:
                    if 'deco_time_limit' in cert and cert['deco_time_limit']:
                        # Update certification level
                        bind.execute(
                            certification_levels.update().where(
                                sa.and_(
                                    certification_levels.c.diving_organization_id == org.id,
                                    certification_levels.c.name == cert['name']
                                )
                            ).values(deco_time_limit=cert['deco_time_limit'])
                        )
            session.commit()
        except Exception as e:
            print(f"Warning: Failed to backfill deco_time_limit: {e}")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certification_levels', 'deco_time_limit')
    # ### end Alembic commands ###