"""align_schema_conventions

Revision ID: 0057
Revises: 0056
Create Date: 2026-01-09 09:25:35.812972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0057'
down_revision = '0056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    def safe_drop_index(index_name, table_name):
        try:
            op.drop_index(index_name, table_name=table_name)
        except Exception as e:
            print(f"Warning: Could not drop index '{index_name}' on table '{table_name}'. It might not exist. Error: {e}")

    def safe_create_index(index_name, table_name, columns, unique=False, **kw):
        try:
            op.create_index(index_name, table_name, columns, unique=unique, **kw)
        except Exception as e:
            print(f"Warning: Could not create index '{index_name}' on table '{table_name}'. It might already exist. Error: {e}")

    # 1. Drop Foreign Keys
    op.drop_constraint('center_comments_ibfk_2', 'center_comments', type_='foreignkey')
    op.drop_constraint('center_comments_ibfk_1', 'center_comments', type_='foreignkey')
    op.drop_constraint('center_dive_sites_ibfk_2', 'center_dive_sites', type_='foreignkey')
    op.drop_constraint('center_dive_sites_ibfk_1', 'center_dive_sites', type_='foreignkey')
    op.drop_constraint('center_ratings_ibfk_1', 'center_ratings', type_='foreignkey')
    op.drop_constraint('center_ratings_ibfk_2', 'center_ratings', type_='foreignkey')
    op.drop_constraint('dive_buddies_ibfk_1', 'dive_buddies', type_='foreignkey')
    op.drop_constraint('dive_buddies_ibfk_2', 'dive_buddies', type_='foreignkey')
    op.drop_constraint('fk_dive_sites_difficulty_id', 'dive_sites', type_='foreignkey')
    op.drop_constraint('fk_dives_difficulty_id', 'dives', type_='foreignkey')
    op.drop_constraint('gear_rental_costs_ibfk_1', 'gear_rental_costs', type_='foreignkey')
    op.drop_constraint('parsed_dive_trips_ibfk_1', 'parsed_dive_trips', type_='foreignkey')
    op.drop_constraint('fk_parsed_dive_trips_difficulty_id', 'parsed_dive_trips', type_='foreignkey')
    op.drop_constraint('refresh_tokens_ibfk_1', 'refresh_tokens', type_='foreignkey')
    op.drop_constraint('site_comments_ibfk_1', 'site_comments', type_='foreignkey')
    op.drop_constraint('site_comments_ibfk_2', 'site_comments', type_='foreignkey')
    op.drop_constraint('site_media_ibfk_1', 'site_media', type_='foreignkey')
    op.drop_constraint('site_ratings_ibfk_2', 'site_ratings', type_='foreignkey')
    op.drop_constraint('site_ratings_ibfk_1', 'site_ratings', type_='foreignkey')

    # 2. Drop Old Indexes
    safe_drop_index('idx_center_id', table_name='center_comments')
    safe_drop_index('idx_user_id', table_name='center_comments')
    safe_drop_index('idx_center_dive_sites_currency', table_name='center_dive_sites')
    safe_drop_index('idx_center_id', table_name='center_dive_sites')
    safe_drop_index('idx_site_id', table_name='center_dive_sites')
    safe_drop_index('unique_center_site', table_name='center_dive_sites')
    safe_drop_index('idx_center_id', table_name='center_ratings')
    safe_drop_index('idx_user_id', table_name='center_ratings')
    safe_drop_index('unique_user_center_rating', table_name='center_ratings')
    safe_drop_index('code', table_name='difficulty_levels')
    safe_drop_index('idx_dive_buddies_dive_id', table_name='dive_buddies')
    safe_drop_index('idx_dive_buddies_user_id', table_name='dive_buddies')
    safe_drop_index('idx_dive_routes_dive_site_active', table_name='dive_routes')
    safe_drop_index('idx_dive_routes_route_type', table_name='dive_routes')
    safe_drop_index('unique_dive_site_alias', table_name='dive_site_aliases')
    safe_drop_index('idx_dive_sites_created_at', table_name='dive_sites')
    safe_drop_index('idx_dive_sites_difficulty_id', table_name='dive_sites')
    safe_drop_index('idx_dive_sites_updated_at', table_name='dive_sites')
    safe_drop_index('idx_dive_sites_view_count', table_name='dive_sites')
    safe_drop_index('idx_location', table_name='dive_sites')
    safe_drop_index('idx_name', table_name='dive_sites')
    safe_drop_index('idx_dives_created_at', table_name='dives')
    safe_drop_index('idx_dives_difficulty_id', table_name='dives')
    safe_drop_index('idx_dives_dive_date', table_name='dives')
    safe_drop_index('idx_dives_duration', table_name='dives')
    safe_drop_index('idx_dives_max_depth', table_name='dives')
    safe_drop_index('idx_dives_updated_at', table_name='dives')
    safe_drop_index('idx_dives_user_rating', table_name='dives')
    safe_drop_index('idx_dives_view_count', table_name='dives')
    safe_drop_index('idx_dives_visibility_rating', table_name='dives')
    safe_drop_index('unique_center_org', table_name='diving_center_organizations')
    safe_drop_index('idx_diving_centers_created_at', table_name='diving_centers')
    safe_drop_index('idx_diving_centers_location', table_name='diving_centers')
    safe_drop_index('idx_diving_centers_updated_at', table_name='diving_centers')
    safe_drop_index('idx_diving_centers_view_count', table_name='diving_centers')
    safe_drop_index('idx_location', table_name='diving_centers')
    safe_drop_index('idx_name', table_name='diving_centers')
    safe_drop_index('token', table_name='email_verification_tokens')
    safe_drop_index('idx_center_id', table_name='gear_rental_costs')
    safe_drop_index('idx_gear_rental_costs_currency', table_name='gear_rental_costs')
    safe_drop_index('idx_received_at', table_name='newsletters')
    safe_drop_index('idx_category', table_name='notification_preferences')
    safe_drop_index('idx_user_id', table_name='notification_preferences')
    safe_drop_index('idx_category', table_name='notifications')
    safe_drop_index('idx_center_id', table_name='parsed_dive_trips')
    safe_drop_index('idx_parsed_dive_trips_difficulty_id', table_name='parsed_dive_trips')
    safe_drop_index('idx_trip_date', table_name='parsed_dive_trips')
    safe_drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    safe_drop_index('idx_refresh_tokens_revoked', table_name='refresh_tokens')
    safe_drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    safe_drop_index('idx_settings_key', table_name='settings')
    safe_drop_index('key', table_name='settings')
    safe_drop_index('idx_site_id', table_name='site_comments')
    safe_drop_index('idx_user_id', table_name='site_comments')
    safe_drop_index('idx_site_id', table_name='site_media')
    safe_drop_index('idx_site_id', table_name='site_ratings')
    safe_drop_index('idx_user_id', table_name='site_ratings')
    safe_drop_index('unique_user_site_rating', table_name='site_ratings')
    safe_drop_index('token', table_name='unsubscribe_tokens')
    safe_drop_index('user_id', table_name='unsubscribe_tokens')
    safe_drop_index('email', table_name='users')
    safe_drop_index('google_id', table_name='users')
    safe_drop_index('idx_email', table_name='users')
    safe_drop_index('idx_google_id', table_name='users')
    safe_drop_index('idx_last_notification_check', table_name='users')
    safe_drop_index('idx_username', table_name='users')
    safe_drop_index('idx_users_buddy_visibility', table_name='users')
    safe_drop_index('idx_users_google_id', table_name='users')
    safe_drop_index('username', table_name='users')
    safe_drop_index('idx_wind_cache_cache_key', table_name='wind_data_cache')
    safe_drop_index('idx_wind_cache_created_at', table_name='wind_data_cache')
    safe_drop_index('idx_wind_cache_latitude', table_name='wind_data_cache')
    safe_drop_index('idx_wind_cache_longitude', table_name='wind_data_cache')
    safe_drop_index('idx_wind_cache_target_datetime', table_name='wind_data_cache')
    safe_drop_index('uq_wind_cache_key', table_name='wind_data_cache')

    # 3. Alter Columns (Schema Changes)
    safe_create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.alter_column('available_tags', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('auth_audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.alter_column('center_dive_sites', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('center_comments', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('center_comments', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('center_ratings', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('dive_buddies', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.alter_column('dive_sites', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('dive_sites', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('diving_centers', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('diving_centers', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    
    op.alter_column('gear_rental_costs', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.alter_column('newsletters', 'received_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('parsed_dive_trips', 'extracted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refresh_tokens', 'last_used_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.alter_column('settings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('site_comments', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('site_comments', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('site_media', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('site_ratings', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    # 4. Create New Indexes
    safe_create_index(op.f('ix_center_comments_diving_center_id'), 'center_comments', ['diving_center_id'], unique=False)
    safe_create_index(op.f('ix_center_comments_id'), 'center_comments', ['id'], unique=False)
    safe_create_index(op.f('ix_center_comments_user_id'), 'center_comments', ['user_id'], unique=False)
    safe_create_index(op.f('ix_center_dive_sites_currency'), 'center_dive_sites', ['currency'], unique=False)
    safe_create_index(op.f('ix_center_dive_sites_dive_site_id'), 'center_dive_sites', ['dive_site_id'], unique=False)
    safe_create_index(op.f('ix_center_dive_sites_diving_center_id'), 'center_dive_sites', ['diving_center_id'], unique=False)
    safe_create_index(op.f('ix_center_dive_sites_id'), 'center_dive_sites', ['id'], unique=False)
    safe_create_index(op.f('ix_center_ratings_diving_center_id'), 'center_ratings', ['diving_center_id'], unique=False)
    safe_create_index(op.f('ix_center_ratings_id'), 'center_ratings', ['id'], unique=False)
    safe_create_index(op.f('ix_center_ratings_user_id'), 'center_ratings', ['user_id'], unique=False)
    safe_create_index(op.f('ix_difficulty_levels_code'), 'difficulty_levels', ['code'], unique=True)
    safe_create_index(op.f('ix_difficulty_levels_id'), 'difficulty_levels', ['id'], unique=False)
    safe_create_index(op.f('ix_difficulty_levels_order_index'), 'difficulty_levels', ['order_index'], unique=False)
    safe_create_index(op.f('ix_dive_buddies_dive_id'), 'dive_buddies', ['dive_id'], unique=False)
    safe_create_index(op.f('ix_dive_buddies_id'), 'dive_buddies', ['id'], unique=False)
    safe_create_index(op.f('ix_dive_buddies_user_id'), 'dive_buddies', ['user_id'], unique=False)
    safe_create_index(op.f('ix_dive_routes_id'), 'dive_routes', ['id'], unique=False)
    # unique constraint is different from index, but using try-except in same logic could work if wrapped manually, or just use op.create_unique_constraint
    # For now, let's leave unique constraint explicit or wrap it too if it fails. Unique constraints often have an index backing them.
    try:
        op.create_unique_constraint('_dive_site_alias_uc', 'dive_site_aliases', ['dive_site_id', 'alias'])
    except Exception as e:
        print(f"Warning: Could not create unique constraint '_dive_site_alias_uc'. Error: {e}")

    safe_create_index(op.f('ix_dive_sites_difficulty_id'), 'dive_sites', ['difficulty_id'], unique=False)
    safe_create_index(op.f('ix_dive_sites_id'), 'dive_sites', ['id'], unique=False)
    safe_create_index(op.f('ix_dive_sites_name'), 'dive_sites', ['name'], unique=False)
    safe_create_index(op.f('ix_dives_difficulty_id'), 'dives', ['difficulty_id'], unique=False)
    safe_create_index(op.f('ix_diving_centers_id'), 'diving_centers', ['id'], unique=False)
    safe_create_index(op.f('ix_diving_centers_name'), 'diving_centers', ['name'], unique=False)
    safe_create_index(op.f('ix_email_config_id'), 'email_config', ['id'], unique=False)
    safe_create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    safe_create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    safe_create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    safe_create_index(op.f('ix_gear_rental_costs_currency'), 'gear_rental_costs', ['currency'], unique=False)
    safe_create_index(op.f('ix_gear_rental_costs_diving_center_id'), 'gear_rental_costs', ['diving_center_id'], unique=False)
    safe_create_index(op.f('ix_gear_rental_costs_id'), 'gear_rental_costs', ['id'], unique=False)
    safe_create_index(op.f('ix_newsletters_received_at'), 'newsletters', ['received_at'], unique=False)
    safe_create_index(op.f('ix_notification_preferences_category'), 'notification_preferences', ['category'], unique=False)
    safe_create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    safe_create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    safe_create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    safe_create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    safe_create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    safe_create_index(op.f('ix_parsed_dive_trips_diving_center_id'), 'parsed_dive_trips', ['diving_center_id'], unique=False)
    safe_create_index(op.f('ix_parsed_dive_trips_id'), 'parsed_dive_trips', ['id'], unique=False)
    safe_create_index(op.f('ix_parsed_dive_trips_trip_date'), 'parsed_dive_trips', ['trip_date'], unique=False)
    safe_create_index(op.f('ix_parsed_dive_trips_trip_difficulty_id'), 'parsed_dive_trips', ['trip_difficulty_id'], unique=False)
    safe_create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    safe_create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    safe_create_index(op.f('ix_site_comments_dive_site_id'), 'site_comments', ['dive_site_id'], unique=False)
    safe_create_index(op.f('ix_site_comments_id'), 'site_comments', ['id'], unique=False)
    safe_create_index(op.f('ix_site_comments_user_id'), 'site_comments', ['user_id'], unique=False)
    safe_create_index(op.f('ix_site_media_dive_site_id'), 'site_media', ['dive_site_id'], unique=False)
    safe_create_index(op.f('ix_site_media_id'), 'site_media', ['id'], unique=False)
    safe_create_index(op.f('ix_site_ratings_dive_site_id'), 'site_ratings', ['dive_site_id'], unique=False)
    safe_create_index(op.f('ix_site_ratings_id'), 'site_ratings', ['id'], unique=False)
    safe_create_index(op.f('ix_site_ratings_user_id'), 'site_ratings', ['user_id'], unique=False)
    safe_create_index(op.f('ix_unsubscribe_tokens_id'), 'unsubscribe_tokens', ['id'], unique=False)
    safe_create_index(op.f('ix_unsubscribe_tokens_token'), 'unsubscribe_tokens', ['token'], unique=True)
    safe_create_index(op.f('ix_unsubscribe_tokens_user_id'), 'unsubscribe_tokens', ['user_id'], unique=True)
    safe_create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    safe_create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    safe_create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    safe_create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    safe_create_index(op.f('ix_wind_data_cache_cache_key'), 'wind_data_cache', ['cache_key'], unique=True)
    safe_create_index(op.f('ix_wind_data_cache_created_at'), 'wind_data_cache', ['created_at'], unique=False)
    safe_create_index(op.f('ix_wind_data_cache_expires_at'), 'wind_data_cache', ['expires_at'], unique=False)
    safe_create_index(op.f('ix_wind_data_cache_id'), 'wind_data_cache', ['id'], unique=False)
    safe_create_index(op.f('ix_wind_data_cache_last_accessed_at'), 'wind_data_cache', ['last_accessed_at'], unique=False)
    safe_create_index(op.f('ix_wind_data_cache_latitude'), 'wind_data_cache', ['latitude'], unique=False)
    safe_create_index(op.f('ix_wind_data_cache_longitude'), 'wind_data_cache', ['longitude'], unique=False)
    safe_create_index(op.f('ix_wind_data_cache_target_datetime'), 'wind_data_cache', ['target_datetime'], unique=False)

    # 5. Recreate Foreign Keys
    op.create_foreign_key(None, 'center_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'center_comments', 'diving_centers', ['diving_center_id'], ['id'])
    op.create_foreign_key(None, 'center_dive_sites', 'dive_sites', ['dive_site_id'], ['id'])
    op.create_foreign_key(None, 'center_dive_sites', 'diving_centers', ['diving_center_id'], ['id'])
    op.create_foreign_key(None, 'center_ratings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'center_ratings', 'diving_centers', ['diving_center_id'], ['id'])
    op.create_foreign_key(None, 'dive_buddies', 'dives', ['dive_id'], ['id'])
    op.create_foreign_key(None, 'dive_buddies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'dive_sites', 'difficulty_levels', ['difficulty_id'], ['id'])
    op.create_foreign_key(None, 'dives', 'difficulty_levels', ['difficulty_id'], ['id'])
    op.create_foreign_key(None, 'gear_rental_costs', 'diving_centers', ['diving_center_id'], ['id'])
    op.create_foreign_key(None, 'parsed_dive_trips', 'difficulty_levels', ['trip_difficulty_id'], ['id'])
    op.create_foreign_key(None, 'parsed_dive_trips', 'newsletters', ['source_newsletter_id'], ['id'])
    op.create_foreign_key(None, 'parsed_dive_trips', 'diving_centers', ['diving_center_id'], ['id'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'site_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'site_comments', 'dive_sites', ['dive_site_id'], ['id'])
    op.create_foreign_key(None, 'site_media', 'dive_sites', ['dive_site_id'], ['id'])
    op.create_foreign_key(None, 'site_ratings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'site_ratings', 'dive_sites', ['dive_site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('available_tags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('center_comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('center_comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_wind_data_cache_target_datetime'), table_name='wind_data_cache')
    op.drop_index(op.f('ix_wind_data_cache_longitude'), table_name='wind_data_cache')
    op.drop_index(op.f('ix_wind_data_cache_latitude'), table_name='wind_data_cache')
    op.drop_index(op.f('ix_wind_data_cache_last_accessed_at'), table_name='wind_data_cache')
    op.drop_index(op.f('ix_wind_data_cache_id'), table_name='wind_data_cache')
    op.drop_index(op.f('ix_wind_data_cache_expires_at'), table_name='wind_data_cache')
    op.drop_index(op.f('ix_wind_data_cache_created_at'), table_name='wind_data_cache')
    op.drop_index(op.f('ix_wind_data_cache_cache_key'), table_name='wind_data_cache')
    op.create_index(op.f('uq_wind_cache_key'), 'wind_data_cache', ['cache_key'], unique=True)
    op.create_index(op.f('idx_wind_cache_target_datetime'), 'wind_data_cache', ['target_datetime'], unique=False)
    op.create_index(op.f('idx_wind_cache_longitude'), 'wind_data_cache', ['longitude'], unique=False)
    op.create_index(op.f('idx_wind_cache_latitude'), 'wind_data_cache', ['latitude'], unique=False)
    op.create_index(op.f('idx_wind_cache_created_at'), 'wind_data_cache', ['created_at'], unique=False)
    op.create_index(op.f('idx_wind_cache_cache_key'), 'wind_data_cache', ['cache_key'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('idx_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('idx_users_buddy_visibility'), 'users', ['buddy_visibility'], unique=False)
    op.create_index(op.f('idx_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_last_notification_check'), 'users', ['last_notification_check'], unique=False)
    op.create_index(op.f('idx_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('idx_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_unsubscribe_tokens_user_id'), table_name='unsubscribe_tokens')
    op.drop_index(op.f('ix_unsubscribe_tokens_token'), table_name='unsubscribe_tokens')
    op.drop_index(op.f('ix_unsubscribe_tokens_id'), table_name='unsubscribe_tokens')
    op.create_index(op.f('user_id'), 'unsubscribe_tokens', ['user_id'], unique=True)
    op.create_index(op.f('token'), 'unsubscribe_tokens', ['token'], unique=True)
    op.drop_constraint(None, 'site_ratings', type_='foreignkey')
    op.drop_constraint(None, 'site_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('site_ratings_ibfk_1'), 'site_ratings', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('site_ratings_ibfk_2'), 'site_ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_site_ratings_user_id'), table_name='site_ratings')
    op.drop_index(op.f('ix_site_ratings_id'), table_name='site_ratings')
    op.drop_index(op.f('ix_site_ratings_dive_site_id'), table_name='site_ratings')
    op.create_index(op.f('unique_user_site_rating'), 'site_ratings', ['user_id', 'dive_site_id'], unique=True)
    op.create_index(op.f('idx_user_id'), 'site_ratings', ['user_id'], unique=False)
    op.create_index(op.f('idx_site_id'), 'site_ratings', ['dive_site_id'], unique=False)
    op.alter_column('site_ratings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'site_media', type_='foreignkey')
    op.create_foreign_key(op.f('site_media_ibfk_1'), 'site_media', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_site_media_id'), table_name='site_media')
    op.drop_index(op.f('ix_site_media_dive_site_id'), table_name='site_media')
    op.create_index(op.f('idx_site_id'), 'site_media', ['dive_site_id'], unique=False)
    op.alter_column('site_media', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'site_comments', type_='foreignkey')
    op.drop_constraint(None, 'site_comments', type_='foreignkey')
    op.create_foreign_key(op.f('site_comments_ibfk_2'), 'site_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('site_comments_ibfk_1'), 'site_comments', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_site_comments_user_id'), table_name='site_comments')
    op.drop_index(op.f('ix_site_comments_id'), table_name='site_comments')
    op.drop_index(op.f('ix_site_comments_dive_site_id'), table_name='site_comments')
    op.create_index(op.f('idx_user_id'), 'site_comments', ['user_id'], unique=False)
    op.create_index(op.f('idx_site_id'), 'site_comments', ['dive_site_id'], unique=False)
    op.alter_column('site_comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('site_comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.create_index(op.f('key'), 'settings', ['key'], unique=True)
    op.create_index(op.f('idx_settings_key'), 'settings', ['key'], unique=False)
    op.alter_column('settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('settings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_ibfk_1'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('refresh_tokens', 'last_used_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'parsed_dive_trips', type_='foreignkey')
    op.drop_constraint(None, 'parsed_dive_trips', type_='foreignkey')
    op.drop_constraint(None, 'parsed_dive_trips', type_='foreignkey')
    op.create_foreign_key(op.f('fk_parsed_dive_trips_difficulty_id'), 'parsed_dive_trips', 'difficulty_levels', ['trip_difficulty_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('parsed_dive_trips_ibfk_1'), 'parsed_dive_trips', 'diving_centers', ['diving_center_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_parsed_dive_trips_trip_difficulty_id'), table_name='parsed_dive_trips')
    op.drop_index(op.f('ix_parsed_dive_trips_trip_date'), table_name='parsed_dive_trips')
    op.drop_index(op.f('ix_parsed_dive_trips_id'), table_name='parsed_dive_trips')
    op.drop_index(op.f('ix_parsed_dive_trips_diving_center_id'), table_name='parsed_dive_trips')
    op.create_index(op.f('idx_trip_date'), 'parsed_dive_trips', ['trip_date'], unique=False)
    op.create_index(op.f('idx_parsed_dive_trips_difficulty_id'), 'parsed_dive_trips', ['trip_difficulty_id'], unique=False)
    op.create_index(op.f('idx_center_id'), 'parsed_dive_trips', ['diving_center_id'], unique=False)
    op.alter_column('parsed_dive_trips', 'extracted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ownership_requests_user_id'), 'ownership_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_ownership_requests_request_status'), 'ownership_requests', ['request_status'], unique=False)
    op.create_index(op.f('ix_ownership_requests_request_date'), 'ownership_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_ownership_requests_diving_center_id'), 'ownership_requests', ['diving_center_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.create_index(op.f('idx_category'), 'notifications', ['category'], unique=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_category'), table_name='notification_preferences')
    op.create_index(op.f('idx_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_index(op.f('idx_category'), 'notification_preferences', ['category'], unique=False)
    op.drop_index(op.f('ix_newsletters_received_at'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_id'), table_name='newsletters')
    op.create_index(op.f('idx_received_at'), 'newsletters', ['received_at'], unique=False)
    op.alter_column('newsletters', 'received_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('newsletters', 'content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'gear_rental_costs', type_='foreignkey')
    op.create_foreign_key(op.f('gear_rental_costs_ibfk_1'), 'gear_rental_costs', 'diving_centers', ['diving_center_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_gear_rental_costs_id'), table_name='gear_rental_costs')
    op.drop_index(op.f('ix_gear_rental_costs_diving_center_id'), table_name='gear_rental_costs')
    op.drop_index(op.f('ix_gear_rental_costs_currency'), table_name='gear_rental_costs')
    op.create_index(op.f('idx_gear_rental_costs_currency'), 'gear_rental_costs', ['currency'], unique=False)
    op.create_index(op.f('idx_center_id'), 'gear_rental_costs', ['diving_center_id'], unique=False)
    op.alter_column('gear_rental_costs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gear_rental_costs', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'EUR'"))
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.create_index(op.f('token'), 'email_verification_tokens', ['token'], unique=True)
    op.drop_index(op.f('ix_email_config_id'), table_name='email_config')
    op.drop_index(op.f('ix_diving_centers_name'), table_name='diving_centers')
    op.drop_index(op.f('ix_diving_centers_id'), table_name='diving_centers')
    op.create_index(op.f('idx_name'), 'diving_centers', ['name'], unique=False)
    op.create_index(op.f('idx_location'), 'diving_centers', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('idx_diving_centers_view_count'), 'diving_centers', ['view_count'], unique=False)
    op.create_index(op.f('idx_diving_centers_updated_at'), 'diving_centers', ['updated_at'], unique=False)
    op.create_index(op.f('idx_diving_centers_location'), 'diving_centers', ['location'], unique=False, mysql_prefix='SPATIAL')
    op.create_index(op.f('idx_diving_centers_created_at'), 'diving_centers', ['created_at'], unique=False)
    op.alter_column('diving_centers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('diving_centers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('unique_center_org'), 'diving_center_organizations', ['diving_center_id', 'diving_organization_id'], unique=True)
    op.drop_constraint(None, 'dives', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dives_difficulty_id'), 'dives', 'difficulty_levels', ['difficulty_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_dives_difficulty_id'), table_name='dives')
    op.create_index(op.f('idx_dives_visibility_rating'), 'dives', ['visibility_rating'], unique=False)
    op.create_index(op.f('idx_dives_view_count'), 'dives', ['view_count'], unique=False)
    op.create_index(op.f('idx_dives_user_rating'), 'dives', ['user_rating'], unique=False)
    op.create_index(op.f('idx_dives_updated_at'), 'dives', ['updated_at'], unique=False)
    op.create_index(op.f('idx_dives_max_depth'), 'dives', ['max_depth'], unique=False)
    op.create_index(op.f('idx_dives_duration'), 'dives', ['duration'], unique=False)
    op.create_index(op.f('idx_dives_dive_date'), 'dives', ['dive_date'], unique=False)
    op.create_index(op.f('idx_dives_difficulty_id'), 'dives', ['difficulty_id'], unique=False)
    op.create_index(op.f('idx_dives_created_at'), 'dives', ['created_at'], unique=False)
    op.drop_constraint(None, 'dive_sites', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dive_sites_difficulty_id'), 'dive_sites', 'difficulty_levels', ['difficulty_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_dive_sites_name'), table_name='dive_sites')
    op.drop_index(op.f('ix_dive_sites_id'), table_name='dive_sites')
    op.drop_index(op.f('ix_dive_sites_difficulty_id'), table_name='dive_sites')
    op.create_index(op.f('idx_name'), 'dive_sites', ['name'], unique=False)
    op.create_index(op.f('idx_location'), 'dive_sites', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('idx_dive_sites_view_count'), 'dive_sites', ['view_count'], unique=False)
    op.create_index(op.f('idx_dive_sites_updated_at'), 'dive_sites', ['updated_at'], unique=False)
    op.create_index(op.f('idx_dive_sites_difficulty_id'), 'dive_sites', ['difficulty_id'], unique=False)
    op.create_index(op.f('idx_dive_sites_created_at'), 'dive_sites', ['created_at'], unique=False)
    op.alter_column('dive_sites', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('dive_sites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('_dive_site_alias_uc', 'dive_site_aliases', type_='unique')
    op.create_index(op.f('unique_dive_site_alias'), 'dive_site_aliases', ['dive_site_id', 'alias'], unique=True)
    op.drop_index(op.f('ix_dive_routes_id'), table_name='dive_routes')
    op.create_index(op.f('idx_dive_routes_route_type'), 'dive_routes', ['route_type'], unique=False)
    op.create_index(op.f('idx_dive_routes_dive_site_active'), 'dive_routes', ['dive_site_id', 'deleted_at'], unique=False)
    op.alter_column('dive_routes', 'route_data',
               existing_type=mysql.JSON(),
               comment='Multi-segment GeoJSON FeatureCollection',
               existing_nullable=False)
    op.drop_constraint(None, 'dive_buddies', type_='foreignkey')
    op.drop_constraint(None, 'dive_buddies', type_='foreignkey')
    op.create_foreign_key(op.f('dive_buddies_ibfk_2'), 'dive_buddies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('dive_buddies_ibfk_1'), 'dive_buddies', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_dive_buddies_user_id'), table_name='dive_buddies')
    op.drop_index(op.f('ix_dive_buddies_id'), table_name='dive_buddies')
    op.drop_index(op.f('ix_dive_buddies_dive_id'), table_name='dive_buddies')
    op.create_index(op.f('idx_dive_buddies_user_id'), 'dive_buddies', ['user_id'], unique=False)
    op.create_index(op.f('idx_dive_buddies_dive_id'), 'dive_buddies', ['dive_id'], unique=False)
    op.alter_column('dive_buddies', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_difficulty_levels_order_index'), table_name='difficulty_levels')
    op.drop_index(op.f('ix_difficulty_levels_id'), table_name='difficulty_levels')
    op.drop_index(op.f('ix_difficulty_levels_code'), table_name='difficulty_levels')
    op.create_index(op.f('code'), 'difficulty_levels', ['code'], unique=True)
    op.drop_constraint(None, 'center_ratings', type_='foreignkey')
    op.drop_constraint(None, 'center_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('center_ratings_ibfk_2'), 'center_ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('center_ratings_ibfk_1'), 'center_ratings', 'diving_centers', ['diving_center_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_center_ratings_user_id'), table_name='center_ratings')
    op.drop_index(op.f('ix_center_ratings_id'), table_name='center_ratings')
    op.drop_index(op.f('ix_center_ratings_diving_center_id'), table_name='center_ratings')
    op.create_index(op.f('unique_user_center_rating'), 'center_ratings', ['user_id', 'diving_center_id'], unique=True)
    op.create_index(op.f('idx_user_id'), 'center_ratings', ['user_id'], unique=False)
    op.create_index(op.f('idx_center_id'), 'center_ratings', ['diving_center_id'], unique=False)
    op.alter_column('center_ratings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'center_dive_sites', type_='foreignkey')
    op.drop_constraint(None, 'center_dive_sites', type_='foreignkey')
    op.create_foreign_key(op.f('center_dive_sites_ibfk_1'), 'center_dive_sites', 'diving_centers', ['diving_center_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('center_dive_sites_ibfk_2'), 'center_dive_sites', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_center_dive_sites_id'), table_name='center_dive_sites')
    op.drop_index(op.f('ix_center_dive_sites_diving_center_id'), table_name='center_dive_sites')
    op.drop_index(op.f('ix_center_dive_sites_dive_site_id'), table_name='center_dive_sites')
    op.drop_index(op.f('ix_center_dive_sites_currency'), table_name='center_dive_sites')
    op.create_index(op.f('unique_center_site'), 'center_dive_sites', ['diving_center_id', 'dive_site_id'], unique=True)
    op.create_index(op.f('idx_site_id'), 'center_dive_sites', ['dive_site_id'], unique=False)
    op.create_index(op.f('idx_center_id'), 'center_dive_sites', ['diving_center_id'], unique=False)
    op.create_index(op.f('idx_center_dive_sites_currency'), 'center_dive_sites', ['currency'], unique=False)
    op.alter_column('center_dive_sites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('center_dive_sites', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'EUR'"))
    op.drop_constraint(None, 'center_comments', type_='foreignkey')
    op.drop_constraint(None, 'center_comments', type_='foreignkey')
    op.create_foreign_key(op.f('center_comments_ibfk_1'), 'center_comments', 'diving_centers', ['diving_center_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('center_comments_ibfk_2'), 'center_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_center_comments_user_id'), table_name='center_comments')
    op.drop_index(op.f('ix_center_comments_id'), table_name='center_comments')
    op.drop_index(op.f('ix_center_comments_diving_center_id'), table_name='center_comments')
    op.create_index(op.f('idx_user_id'), 'center_comments', ['user_id'], unique=False)
    op.create_index(op.f('idx_center_id'), 'center_comments', ['diving_center_id'], unique=False)
    op.alter_column('auth_audit_logs', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('auth_audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    # ### end Alembic commands ###