"""fix_drift_and_restore_fks

Revision ID: 0058
Revises: 0057
Create Date: 2026-01-09 22:06:25.551417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0058'
down_revision = '0057'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    def safe_drop_index(index_name, table_name):
        try:
            op.drop_index(index_name, table_name=table_name)
        except Exception as e:
            print(f"Warning: Could not drop index '{index_name}' on table '{table_name}'. It might not exist. Error: {e}")

    def safe_create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols, **kw):
        try:
            op.create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols, **kw)
        except Exception as e:
            print(f"Warning: Could not create foreign key '{constraint_name}' on table '{source_table}'. It might already exist. Error: {e}")

    # 0. Fix Orphaned Data (Pre-check for Foreign Keys)
    conn = op.get_bind()

    # Refresh tokens that don't belong to any user should be deleted (not reassigned)
    print("Deleting orphaned refresh_tokens...")
    conn.execute(sa.text("DELETE FROM refresh_tokens WHERE user_id NOT IN (SELECT id FROM users)"))

    # Find a user to reassign orphans to (Admin preferred, then any user)
    # Ratings and comments are reassigned to preserve content/scores
    admin_id = conn.execute(sa.text("SELECT id FROM users WHERE is_admin = 1 ORDER BY id LIMIT 1")).scalar()
    if not admin_id:
        admin_id = conn.execute(sa.text("SELECT id FROM users ORDER BY id LIMIT 1")).scalar()

    if admin_id:
        print(f"Reassigning orphaned site_ratings and site_comments to User ID: {admin_id}")
        conn.execute(sa.text(f"UPDATE site_ratings SET user_id = {admin_id} WHERE user_id NOT IN (SELECT id FROM users)"))
        conn.execute(sa.text(f"UPDATE site_comments SET user_id = {admin_id} WHERE user_id NOT IN (SELECT id FROM users)"))
    else:
        print("No users found. Deleting orphaned site_ratings and site_comments.")
        conn.execute(sa.text("DELETE FROM site_ratings WHERE user_id NOT IN (SELECT id FROM users)"))
        conn.execute(sa.text("DELETE FROM site_comments WHERE user_id NOT IN (SELECT id FROM users)"))

    # For orphaned dive_site_id, we just delete them as we can't easily guess a valid site
    print("Deleting records with invalid dive_site_id...")
    conn.execute(sa.text("DELETE FROM site_ratings WHERE dive_site_id NOT IN (SELECT id FROM dive_sites)"))
    conn.execute(sa.text("DELETE FROM site_comments WHERE dive_site_id NOT IN (SELECT id FROM dive_sites)"))

    op.alter_column('auth_audit_logs', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('available_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    safe_drop_index(op.f('ix_available_tags_id'), table_name='available_tags')
    op.alter_column('center_dive_sites', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'EUR'"))
    op.alter_column('dive_routes', 'route_data',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Multi-segment GeoJSON FeatureCollection',
               existing_nullable=False)
    safe_drop_index(op.f('ix_dive_site_tags_id'), table_name='dive_site_tags')
    safe_drop_index(op.f('ix_diving_center_organizations_id'), table_name='diving_center_organizations')
    op.alter_column('gear_rental_costs', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'EUR'"))
    
    # Recreate FKs with proper ondelete rules where applicable
    safe_create_foreign_key(None, 'parsed_dive_trips', 'newsletters', ['source_newsletter_id'], ['id'], ondelete='SET NULL')
    safe_drop_index(op.f('ix_parsed_dives_id'), table_name='parsed_dives')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    safe_create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    safe_create_foreign_key(None, 'site_comments', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    safe_create_foreign_key(None, 'site_ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    safe_create_foreign_key(None, 'site_ratings', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_ratings', type_='foreignkey')
    op.drop_constraint(None, 'site_ratings', type_='foreignkey')
    op.drop_constraint(None, 'site_comments', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_parsed_dives_id'), 'parsed_dives', ['id'], unique=False)
    op.drop_constraint(None, 'parsed_dive_trips', type_='foreignkey')
    op.alter_column('newsletters', 'content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('gear_rental_costs', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'EUR'"))
    op.create_index(op.f('ix_diving_center_organizations_id'), 'diving_center_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_dive_site_tags_id'), 'dive_site_tags', ['id'], unique=False)
    op.alter_column('dive_routes', 'route_data',
               existing_type=mysql.JSON(),
               comment='Multi-segment GeoJSON FeatureCollection',
               existing_nullable=False)
    op.alter_column('center_dive_sites', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'EUR'"))
    op.create_index(op.f('ix_available_tags_id'), 'available_tags', ['id'], unique=False)
    op.alter_column('available_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('auth_audit_logs', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
