"""add_media_order_to_dive_sites

Revision ID: b7442a06a5d3
Revises: 0060
Create Date: 2026-01-14 20:13:53.381930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0061'
down_revision = '0060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive_sites', sa.Column('media_order', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dive_sites', 'media_order')
    # ### end Alembic commands ### 