"""add_debug_data_to_chatfeedback

Revision ID: 0064
Revises: 0063
Create Date: 2026-02-14 15:07:33.810281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0064'
down_revision = '0063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_feedback', sa.Column('debug_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_feedback', 'debug_data')
    # ### end Alembic commands ###
