"""add_token_usage_to_chat_messages

Revision ID: bc3ec4b47c91
Revises: 0065
Create Date: 2026-02-14 18:56:04.877983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0066'
down_revision = '0065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tokens_input', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('tokens_output', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('tokens_cached', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('tokens_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tokens_total')
    op.drop_column('chat_messages', 'tokens_cached')
    op.drop_column('chat_messages', 'tokens_output')
    op.drop_column('chat_messages', 'tokens_input')
    # ### end Alembic commands ### 