"""add_user_friendships

Revision ID: 0069
Revises: 0068
Create Date: 2026-02-22 20:28:29.887927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0069'
down_revision = '0068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='_user_friendship_uc')
    )
    op.create_index(op.f('ix_user_friendships_friend_id'), 'user_friendships', ['friend_id'], unique=False)
    op.create_index(op.f('ix_user_friendships_id'), 'user_friendships', ['id'], unique=False)
    op.create_index(op.f('ix_user_friendships_user_id'), 'user_friendships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_friendships_user_id'), table_name='user_friendships')
    op.drop_index(op.f('ix_user_friendships_id'), table_name='user_friendships')
    op.drop_index(op.f('ix_user_friendships_friend_id'), table_name='user_friendships')
    op.drop_table('user_friendships')
    # ### end Alembic commands ### 