"""add_personal_access_tokens_table

Revision ID: 0070
Revises: 0069
Create Date: 2026-03-17 22:28:24.217488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0070'
down_revision = '0069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pat_active', 'personal_access_tokens', ['is_active'], unique=False)
    op.create_index('idx_pat_expires', 'personal_access_tokens', ['expires_at'], unique=False)
    op.create_index('idx_pat_prefix', 'personal_access_tokens', ['token_prefix'], unique=False)
    op.create_index('idx_pat_token_hash', 'personal_access_tokens', ['token_hash'], unique=False)
    op.create_index('idx_pat_user_id', 'personal_access_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_id'), 'personal_access_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_personal_access_tokens_token_prefix'), 'personal_access_tokens', ['token_prefix'], unique=False)
    op.create_index(op.f('ix_personal_access_tokens_user_id'), 'personal_access_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_access_tokens_user_id'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_token_prefix'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_token_hash'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_id'), table_name='personal_access_tokens')
    op.drop_index('idx_pat_user_id', table_name='personal_access_tokens')
    op.drop_index('idx_pat_token_hash', table_name='personal_access_tokens')
    op.drop_index('idx_pat_prefix', table_name='personal_access_tokens')
    op.drop_index('idx_pat_expires', table_name='personal_access_tokens')
    op.drop_index('idx_pat_active', table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    # ### end Alembic commands ### 