"""add_soft_delete_to_dive_sites

Revision ID: 0071
Revises: 0070
Create Date: 2026-03-19 19:19:39.168739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0071'
down_revision = '0070'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('center_dive_sites_ibfk_1'), 'center_dive_sites', type_='foreignkey')
    op.create_foreign_key(None, 'center_dive_sites', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dive_routes_ibfk_3'), 'dive_routes', type_='foreignkey')
    op.create_foreign_key(None, 'dive_routes', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dive_site_aliases_ibfk_1'), 'dive_site_aliases', type_='foreignkey')
    op.create_foreign_key(None, 'dive_site_aliases', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('dive_site_tags_ibfk_1'), 'dive_site_tags', type_='foreignkey')
    op.create_foreign_key(None, 'dive_site_tags', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    op.add_column('dive_sites', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_dive_sites_deleted_at'), 'dive_sites', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('dives_ibfk_1'), 'dives', type_='foreignkey')
    op.create_foreign_key(None, 'dives', 'dive_sites', ['dive_site_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('parsed_dives_ibfk_2'), 'parsed_dives', type_='foreignkey')
    op.create_foreign_key(None, 'parsed_dives', 'dive_sites', ['dive_site_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('site_media_ibfk_1'), 'site_media', type_='foreignkey')
    op.create_foreign_key(None, 'site_media', 'dive_sites', ['dive_site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_media', type_='foreignkey')
    op.create_foreign_key(op.f('site_media_ibfk_1'), 'site_media', 'dive_sites', ['dive_site_id'], ['id'])
    op.drop_constraint(None, 'parsed_dives', type_='foreignkey')
    op.create_foreign_key(op.f('parsed_dives_ibfk_2'), 'parsed_dives', 'dive_sites', ['dive_site_id'], ['id'])
    op.drop_constraint(None, 'dives', type_='foreignkey')
    op.create_foreign_key(op.f('dives_ibfk_1'), 'dives', 'dive_sites', ['dive_site_id'], ['id'])
    op.drop_index(op.f('ix_dive_sites_deleted_at'), table_name='dive_sites')
    op.drop_column('dive_sites', 'deleted_at')
    op.drop_constraint(None, 'dive_site_tags', type_='foreignkey')
    op.create_foreign_key(op.f('dive_site_tags_ibfk_1'), 'dive_site_tags', 'dive_sites', ['dive_site_id'], ['id'])
    op.drop_constraint(None, 'dive_site_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('dive_site_aliases_ibfk_1'), 'dive_site_aliases', 'dive_sites', ['dive_site_id'], ['id'])
    op.drop_constraint(None, 'dive_routes', type_='foreignkey')
    op.create_foreign_key(op.f('dive_routes_ibfk_3'), 'dive_routes', 'dive_sites', ['dive_site_id'], ['id'])
    op.drop_constraint(None, 'center_dive_sites', type_='foreignkey')
    op.create_foreign_key(op.f('center_dive_sites_ibfk_1'), 'center_dive_sites', 'dive_sites', ['dive_site_id'], ['id'])
    # ### end Alembic commands ### 