"""add_enable_push_to_notification_preferences

Revision ID: 0076
Revises: 0075
Create Date: 2026-03-28 08:40:54.620746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0076'
down_revision = '0075'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('enable_push', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'enable_push')
    # ### end Alembic commands ###
