"""add status to dive sites

Revision ID: 0077
Revises: 0076
Create Date: 2026-03-29 16:09:51.447356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0077'
down_revision = '0076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dive_sites', sa.Column('status', sa.Enum('approved', 'pending', 'rejected', name='dive_site_status'), server_default='approved', nullable=False))
    op.create_index(op.f('ix_dive_sites_status'), 'dive_sites', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dive_sites_status'), table_name='dive_sites')
    op.drop_column('dive_sites', 'status')
    # ### end Alembic commands ###
