"""add_b2c_managers_and_logo

Revision ID: 0079
Revises: 0078
Create Date: 2026-04-01 18:37:20.987293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0079'
down_revision = '0078'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diving_center_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diving_center_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diving_center_id'], ['diving_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diving_center_id', 'user_id', name='uix_center_manager')
    )
    op.create_index(op.f('ix_diving_center_managers_id'), 'diving_center_managers', ['id'], unique=False)
    op.add_column('diving_centers', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diving_centers', 'logo_url')
    op.drop_index(op.f('ix_diving_center_managers_id'), table_name='diving_center_managers')
    op.drop_table('diving_center_managers')
    # ### end Alembic commands ###
