"""add_b2c_chat_models

Revision ID: 0080
Revises: 0079
Create Date: 2026-04-01 18:53:44.812069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0080'
down_revision = '0079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diving_center_chat_settings',
    sa.Column('diving_center_id', sa.Integer(), nullable=False),
    sa.Column('auto_greeting', sa.Text(), nullable=True),
    sa.Column('quick_replies', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['diving_center_id'], ['diving_centers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diving_center_id')
    )
    op.create_table('diving_center_followers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diving_center_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diving_center_id'], ['diving_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'diving_center_id')
    )
    op.add_column('user_chat_rooms', sa.Column('diving_center_id', sa.Integer(), nullable=True))
    op.add_column('user_chat_rooms', sa.Column('is_broadcast', sa.Boolean(), nullable=False))
    op.add_column('user_chat_rooms', sa.Column('business_status', sa.Enum('UNREAD', 'READ', 'RESOLVED', name='businesschatstatus'), nullable=False))
    op.add_column('user_chat_rooms', sa.Column('last_responded_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_chat_rooms', 'diving_centers', ['diving_center_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_chat_rooms', 'users', ['last_responded_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'user_chat_rooms', type_='foreignkey')
    op.drop_column('user_chat_rooms', 'last_responded_by_id')
    op.drop_column('user_chat_rooms', 'business_status')
    op.drop_column('user_chat_rooms', 'is_broadcast')
    op.drop_column('user_chat_rooms', 'diving_center_id')
    op.drop_table('diving_center_followers')
    op.drop_table('diving_center_chat_settings')
    # ### end Alembic commands ###
