"""add dive site edit requests

Revision ID: 0081
Revises: 0080
Create Date: 2026-04-05 09:05:09.017527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0081'
down_revision = '0080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dive_site_edit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dive_site_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='editrequeststatus'), nullable=False),
    sa.Column('edit_type', sa.Enum('site_data', 'media_addition', 'media_update', 'media_deletion', name='editrequesttype'), nullable=False),
    sa.Column('proposed_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dive_site_id'], ['dive_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dive_site_edit_requests_dive_site_id'), 'dive_site_edit_requests', ['dive_site_id'], unique=False)
    op.create_index(op.f('ix_dive_site_edit_requests_id'), 'dive_site_edit_requests', ['id'], unique=False)
    op.create_index(op.f('ix_dive_site_edit_requests_requested_by_id'), 'dive_site_edit_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_dive_site_edit_requests_status'), 'dive_site_edit_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dive_site_edit_requests_status'), table_name='dive_site_edit_requests')
    op.drop_index(op.f('ix_dive_site_edit_requests_requested_by_id'), table_name='dive_site_edit_requests')
    op.drop_index(op.f('ix_dive_site_edit_requests_id'), table_name='dive_site_edit_requests')
    op.drop_index(op.f('ix_dive_site_edit_requests_dive_site_id'), table_name='dive_site_edit_requests')
    op.drop_table('dive_site_edit_requests')
    # ### end Alembic commands ### 