"""add_message_type_to_chat

Revision ID: 0081
Revises: 0080
Create Date: 2026-04-01 19:17:11.665486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0081'
down_revision = '0080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat_messages', sa.Column('message_type', sa.String(length=50), nullable=False, server_default='TEXT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat_messages', 'message_type')
    # ### end Alembic commands ###
