"""add tag types to edit requests

Revision ID: 0082
Revises: 0081
Create Date: 2026-04-05 13:53:47.357713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0082'
down_revision = '0081'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE dive_site_edit_requests MODIFY COLUMN edit_type ENUM('site_data', 'media_addition', 'media_update', 'media_deletion', 'tag_addition', 'tag_removal') NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE dive_site_edit_requests MODIFY COLUMN edit_type ENUM('site_data', 'media_addition', 'media_update', 'media_deletion') NOT NULL")
    # ### end Alembic commands ###

