"""Add user_id to site_media

Revision ID: 0082
Revises: 0081
Create Date: 2026-04-14 15:52:48.462794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0082'
down_revision = '0081'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_media', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_site_media_user_id'), 'site_media', ['user_id'], unique=False)
    op.create_foreign_key('fk_site_media_user_id_users', 'site_media', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Data migration: Attribute existing site media to the dive site creator
    op.execute("""
        UPDATE site_media sm
        JOIN dive_sites ds ON sm.dive_site_id = ds.id
        JOIN users u ON ds.created_by = u.id
        SET sm.user_id = ds.created_by
        WHERE sm.user_id IS NULL AND ds.created_by IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_site_media_user_id_users', 'site_media', type_='foreignkey')
    op.drop_index(op.f('ix_site_media_user_id'), table_name='site_media')
    op.drop_column('site_media', 'user_id')
    # ### end Alembic commands ### 
 