"""add_chat_archiving

Revision ID: 0083
Revises: 0082
Create Date: 2026-04-01 22:55:36.176994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0083'
down_revision = '0082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat_room_members', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('user_chat_rooms', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chat_rooms', 'is_archived')
    op.drop_column('user_chat_room_members', 'is_archived')
    # ### end Alembic commands ###
