"""add_avatar_fields_to_users

Revision ID: 0084
Revises: 0083
Create Date: 2026-04-20 22:16:40.860260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0084'
down_revision = '0083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_type', sa.String(length=20), nullable=True, server_default='google'))
    op.add_column('users', sa.Column('google_avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_avatar_url')
    op.drop_column('users', 'avatar_type')
    # ### end Alembic commands ###
