"""Add CenterMedia table

Revision ID: 0085
Revises: 0084
Create Date: 2026-05-02 17:38:54.610370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0085'
down_revision = '0084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diving_center_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.Enum('photo', 'video', 'dive_plan', 'external_link', name='mediatype'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('medium_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diving_center_id'], ['diving_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_center_media_diving_center_id'), 'center_media', ['diving_center_id'], unique=False)
    op.create_index(op.f('ix_center_media_id'), 'center_media', ['id'], unique=False)
    op.create_index(op.f('ix_center_media_user_id'), 'center_media', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_center_media_user_id'), table_name='center_media')
    op.drop_index(op.f('ix_center_media_id'), table_name='center_media')
    op.drop_index(op.f('ix_center_media_diving_center_id'), table_name='center_media')
    op.drop_table('center_media')
    # ### end Alembic commands ###
