"""cascade_delete_dive_buddies

Revision ID: 0086
Revises: 0085
Create Date: 2026-05-08 08:31:11.617309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0086'
down_revision = '0085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dive_buddies_ibfk_1', 'dive_buddies', type_='foreignkey')
    op.create_foreign_key('dive_buddies_ibfk_1', 'dive_buddies', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dive_buddies_ibfk_1', 'dive_buddies', type_='foreignkey')
    op.create_foreign_key('dive_buddies_ibfk_1', 'dive_buddies', 'dives', ['dive_id'], ['id'])
    # ### end Alembic commands ###
