"""cascade_delete_dive_buddies

Revision ID: 0086
Revises: 0085
Create Date: 2026-05-08 08:31:11.617309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '0086'
down_revision = '0085'
branch_labels = None
depends_on = None

def get_fk_name(table_name, column_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for fk in inspector.get_foreign_keys(table_name):
        if column_name in fk['constrained_columns']:
            return fk['name']
    return None

def safe_drop_fk(table_name, column_name):
    fk_name = get_fk_name(table_name, column_name)
    if fk_name:
        op.drop_constraint(fk_name, table_name, type_='foreignkey')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_fk('dive_buddies', 'dive_id')
    op.create_foreign_key(None, 'dive_buddies', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_fk('dive_buddies', 'dive_id')
    op.create_foreign_key(None, 'dive_buddies', 'dives', ['dive_id'], ['id'])
    # ### end Alembic commands ###
