"""cascade_delete_dive_media_tags

Revision ID: 0087
Revises: 0086
Create Date: 2026-05-08 09:14:59.192274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0087'
down_revision = '0086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dive_media_ibfk_1', 'dive_media', type_='foreignkey')
    op.create_foreign_key('dive_media_ibfk_1', 'dive_media', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dive_tags_ibfk_1', 'dive_tags', type_='foreignkey')
    op.drop_constraint('dive_tags_ibfk_2', 'dive_tags', type_='foreignkey')
    op.create_foreign_key('dive_tags_ibfk_1', 'dive_tags', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('dive_tags_ibfk_2', 'dive_tags', 'available_tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dive_tags_ibfk_2', 'dive_tags', type_='foreignkey')
    op.drop_constraint('dive_tags_ibfk_1', 'dive_tags', type_='foreignkey')
    op.create_foreign_key('dive_tags_ibfk_1', 'dive_tags', 'dives', ['dive_id'], ['id'])
    op.create_foreign_key('dive_tags_ibfk_2', 'dive_tags', 'available_tags', ['tag_id'], ['id'])
    op.drop_constraint('dive_media_ibfk_1', 'dive_media', type_='foreignkey')
    op.create_foreign_key('dive_media_ibfk_1', 'dive_media', 'dives', ['dive_id'], ['id'])
    # ### end Alembic commands ###
