"""cascade_delete_dive_media_tags

Revision ID: 0087
Revises: 0086
Create Date: 2026-05-08 09:14:59.192274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '0087'
down_revision = '0086'
branch_labels = None
depends_on = None

def get_fk_name(table_name, column_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for fk in inspector.get_foreign_keys(table_name):
        if column_name in fk['constrained_columns']:
            return fk['name']
    return None

def safe_drop_fk(table_name, column_name):
    fk_name = get_fk_name(table_name, column_name)
    if fk_name:
        op.drop_constraint(fk_name, table_name, type_='foreignkey')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_fk('dive_media', 'dive_id')
    op.create_foreign_key(None, 'dive_media', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    
    safe_drop_fk('dive_tags', 'dive_id')
    safe_drop_fk('dive_tags', 'tag_id')
    op.create_foreign_key(None, 'dive_tags', 'dives', ['dive_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dive_tags', 'available_tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_fk('dive_tags', 'tag_id')
    safe_drop_fk('dive_tags', 'dive_id')
    op.create_foreign_key(None, 'dive_tags', 'dives', ['dive_id'], ['id'])
    op.create_foreign_key(None, 'dive_tags', 'available_tags', ['tag_id'], ['id'])
    
    safe_drop_fk('dive_media', 'dive_id')
    op.create_foreign_key(None, 'dive_media', 'dives', ['dive_id'], ['id'])
    # ### end Alembic commands ###
