"""dive_set_null_cascades

Revision ID: 0088
Revises: 0087
Create Date: 2026-05-08 09:39:11.897207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0088'
down_revision = '0087'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dives_diving_center_id', 'dives', type_='foreignkey')
    op.drop_constraint('fk_dives_selected_route_id', 'dives', type_='foreignkey')
    op.drop_constraint('dives_ibfk_3', 'dives', type_='foreignkey')
    op.create_foreign_key('fk_dives_difficulty_id', 'dives', 'difficulty_levels', ['difficulty_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_dives_diving_center_id', 'dives', 'diving_centers', ['diving_center_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_dives_selected_route_id', 'dives', 'dive_routes', ['selected_route_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dives_selected_route_id', 'dives', type_='foreignkey')
    op.drop_constraint('fk_dives_diving_center_id', 'dives', type_='foreignkey')
    op.drop_constraint('fk_dives_difficulty_id', 'dives', type_='foreignkey')
    op.create_foreign_key('dives_ibfk_3', 'dives', 'difficulty_levels', ['difficulty_id'], ['id'])
    op.create_foreign_key('fk_dives_selected_route_id', 'dives', 'dive_routes', ['selected_route_id'], ['id'])
    op.create_foreign_key('fk_dives_diving_center_id', 'dives', 'diving_centers', ['diving_center_id'], ['id'])
    # ### end Alembic commands ###
