"""dive_set_null_cascades

Revision ID: 0088
Revises: 0087
Create Date: 2026-05-08 09:39:11.897207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '0088'
down_revision = '0087'
branch_labels = None
depends_on = None

def get_fk_name(table_name, column_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for fk in inspector.get_foreign_keys(table_name):
        if column_name in fk['constrained_columns']:
            return fk['name']
    return None

def safe_drop_fk(table_name, column_name):
    fk_name = get_fk_name(table_name, column_name)
    if fk_name:
        op.drop_constraint(fk_name, table_name, type_='foreignkey')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_fk('dives', 'diving_center_id')
    safe_drop_fk('dives', 'selected_route_id')
    safe_drop_fk('dives', 'difficulty_id')
    
    op.create_foreign_key(None, 'dives', 'difficulty_levels', ['difficulty_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dives', 'diving_centers', ['diving_center_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dives', 'dive_routes', ['selected_route_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_fk('dives', 'selected_route_id')
    safe_drop_fk('dives', 'diving_center_id')
    safe_drop_fk('dives', 'difficulty_id')
    
    op.create_foreign_key(None, 'dives', 'difficulty_levels', ['difficulty_id'], ['id'])
    op.create_foreign_key(None, 'dives', 'dive_routes', ['selected_route_id'], ['id'])
    op.create_foreign_key(None, 'dives', 'diving_centers', ['diving_center_id'], ['id'])
    # ### end Alembic commands ###
