"""fix_ownership_requests_user_fk

Revision ID: 0090
Revises: 0089
Create Date: 2026-05-08 11:14:34.446423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0090'
down_revision = '0089'
branch_labels = None
depends_on = None


from sqlalchemy.engine.reflection import Inspector

def get_fk_name(table_name, column_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for fk in inspector.get_foreign_keys(table_name):
        if column_name in fk['constrained_columns']:
            return fk['name']
    return None

def safe_drop_fk(table_name, column_name):
    fk_name = get_fk_name(table_name, column_name)
    if fk_name:
        op.drop_constraint(fk_name, table_name, type_='foreignkey')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ownership_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_fk('ownership_requests', 'user_id')
    # ### end Alembic commands ###
