"""Add dive site aliases table for multilingual support

Revision ID: 29fac01eff2e
Revises: add_parseddive_table_simple
Create Date: 2025-08-08 19:15:27.618776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29fac01eff2e'
down_revision = 'add_parseddive_table_simple'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create dive site aliases table
    op.create_table('dive_site_aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dive_site_id', sa.Integer(), nullable=False),
        sa.Column('alias', sa.String(length=255), nullable=False),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['dive_site_id'], ['dive_sites.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dive_site_aliases_alias'), 'dive_site_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_dive_site_aliases_dive_site_id'), 'dive_site_aliases', ['dive_site_id'], unique=False)
    op.create_index(op.f('ix_dive_site_aliases_id'), 'dive_site_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_dive_site_aliases_language'), 'dive_site_aliases', ['language'], unique=False)
    
    # Add unique constraint to prevent duplicate aliases for the same dive site
    op.create_unique_constraint('unique_dive_site_alias', 'dive_site_aliases', ['dive_site_id', 'alias'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop dive site aliases table
    op.drop_constraint('unique_dive_site_alias', 'dive_site_aliases', type_='unique')
    op.drop_index(op.f('ix_dive_site_aliases_language'), table_name='dive_site_aliases')
    op.drop_index(op.f('ix_dive_site_aliases_id'), table_name='dive_site_aliases')
    op.drop_index(op.f('ix_dive_site_aliases_dive_site_id'), table_name='dive_site_aliases')
    op.drop_index(op.f('ix_dive_site_aliases_alias'), table_name='dive_site_aliases')
    op.drop_table('dive_site_aliases')
    
    # ### end Alembic commands ### 