"""Add ParsedDive table for multiple dives per trip

Revision ID: add_parseddive_table_simple
Revises: parsed_trip_enhance
Create Date: 2025-08-05 02:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_parseddive_table_simple'
down_revision = 'parsed_trip_enhance'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if dive_site_id column exists in parsed_dive_trips table
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('parsed_dive_trips')]
    
    if 'dive_site_id' in columns:
        # Drop foreign key constraint first, then remove dive_site_id from parsed_dive_trips
        op.drop_constraint('parsed_dive_trips_ibfk_2', 'parsed_dive_trips', type_='foreignkey')
        op.drop_column('parsed_dive_trips', 'dive_site_id')
    
    # Create parsed_dives table
    op.create_table('parsed_dives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('dive_site_id', sa.Integer(), nullable=True),
    sa.Column('dive_number', sa.Integer(), nullable=False),
    sa.Column('dive_time', sa.Time(), nullable=True),
    sa.Column('dive_duration', sa.Integer(), nullable=True),
    sa.Column('dive_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dive_site_id'], ['dive_sites.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['parsed_dive_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_dives_id'), 'parsed_dives', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_dives_trip_id'), 'parsed_dives', ['trip_id'], unique=False)
    op.create_index(op.f('ix_parsed_dives_dive_site_id'), 'parsed_dives', ['dive_site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_dives_dive_site_id'), table_name='parsed_dives')
    op.drop_index(op.f('ix_parsed_dives_trip_id'), table_name='parsed_dives')
    op.drop_index(op.f('ix_parsed_dives_id'), table_name='parsed_dives')
    op.drop_table('parsed_dives')
    
    # Add dive_site_id back to parsed_dive_trips
    op.add_column('parsed_dive_trips', sa.Column('dive_site_id', sa.Integer(), nullable=True))
    op.create_foreign_key('parsed_dive_trips_ibfk_2', 'parsed_dive_trips', 'dive_sites', ['dive_site_id'], ['id'])
    # ### end Alembic commands ### 