"""Add diving organizations and user certifications simple

Revision ID: c85d7af66778
Revises: 0005
Create Date: 2025-07-29 21:02:18.364789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c85d7af66778'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create diving_organizations table
    op.create_table('diving_organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('acronym', sa.String(length=20), nullable=False),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('logo_url', sa.String(length=500), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('founded_year', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diving_organizations_acronym'), 'diving_organizations', ['acronym'], unique=True)
    op.create_index(op.f('ix_diving_organizations_id'), 'diving_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_diving_organizations_name'), 'diving_organizations', ['name'], unique=True)
    
    # Create diving_center_organizations table
    op.create_table('diving_center_organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('diving_center_id', sa.Integer(), nullable=False),
        sa.Column('diving_organization_id', sa.Integer(), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['diving_center_id'], ['diving_centers.id'], ),
        sa.ForeignKeyConstraint(['diving_organization_id'], ['diving_organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diving_center_organizations_diving_center_id'), 'diving_center_organizations', ['diving_center_id'], unique=False)
    op.create_index(op.f('ix_diving_center_organizations_diving_organization_id'), 'diving_center_organizations', ['diving_organization_id'], unique=False)
    op.create_index(op.f('ix_diving_center_organizations_id'), 'diving_center_organizations', ['id'], unique=False)
    op.create_unique_constraint('unique_center_org', 'diving_center_organizations', ['diving_center_id', 'diving_organization_id'])
    
    # Create user_certifications table
    op.create_table('user_certifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('diving_organization_id', sa.Integer(), nullable=False),
        sa.Column('certification_name', sa.String(length=100), nullable=False),
        sa.Column('certification_level', sa.String(length=100), nullable=True),
        sa.Column('certification_date', sa.Date(), nullable=True),
        sa.Column('certification_number', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['diving_organization_id'], ['diving_organizations.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certifications_certification_name'), 'user_certifications', ['certification_name'], unique=False)
    op.create_index(op.f('ix_user_certifications_diving_organization_id'), 'user_certifications', ['diving_organization_id'], unique=False)
    op.create_index(op.f('ix_user_certifications_id'), 'user_certifications', ['id'], unique=False)
    op.create_index(op.f('ix_user_certifications_user_id'), 'user_certifications', ['user_id'], unique=False)
    
    # Remove diving_certification column from users table
    op.drop_column('users', 'diving_certification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add diving_certification column back to users table
    op.add_column('users', sa.Column('diving_certification', mysql.VARCHAR(length=100), nullable=True))
    
    # Drop user_certifications table
    op.drop_index(op.f('ix_user_certifications_user_id'), table_name='user_certifications')
    op.drop_index(op.f('ix_user_certifications_id'), table_name='user_certifications')
    op.drop_index(op.f('ix_user_certifications_diving_organization_id'), table_name='user_certifications')
    op.drop_index(op.f('ix_user_certifications_certification_name'), table_name='user_certifications')
    op.drop_table('user_certifications')
    
    # Drop diving_center_organizations table
    op.drop_constraint('unique_center_org', 'diving_center_organizations', type_='unique')
    op.drop_index(op.f('ix_diving_center_organizations_id'), table_name='diving_center_organizations')
    op.drop_index(op.f('ix_diving_center_organizations_diving_organization_id'), table_name='diving_center_organizations')
    op.drop_index(op.f('ix_diving_center_organizations_diving_center_id'), table_name='diving_center_organizations')
    op.drop_table('diving_center_organizations')
    
    # Drop diving_organizations table
    op.drop_index(op.f('ix_diving_organizations_name'), table_name='diving_organizations')
    op.drop_index(op.f('ix_diving_organizations_id'), table_name='diving_organizations')
    op.drop_index(op.f('ix_diving_organizations_acronym'), table_name='diving_organizations')
    op.drop_table('diving_organizations')
    # ### end Alembic commands ### 